src/Entity/Payement.php
<?php

namespace App\Entity;

use App\Repository\PayementRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PayementRepository::class)
 */
class Payement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $montant;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity=Participants::class, inversedBy="payement" , cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $participant_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMontant(): ?int
    {
        return $this->montant;
    }

    public function setMontant(int $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getParticipantId(): ?Participants
    {
        return $this->participant_id;
    }

    public function setParticipantId(?Participants $participant_id): self
    {
        $this->participant_id = $participant_id;

        return $this;
    }
}

src/Form/PayementType.php
<?php

namespace App\Form;

use App\Entity\Participants;
use App\Entity\Payement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Form\ParticipantsType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;

class PayementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('montant', NumberType::class, [
                'label' => 'Votre participation'
            ])
            ->add('participant_id', ParticipantsType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Payement::class,
        ]);
    }
}

src/Controller/PayementController.php
<?php

namespace App\Controller;

use App\Entity\Campaign;
use App\Entity\Payement;
use App\Form\PayementType;
use App\Repository\PayementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Stripe\Stripe;
use Stripe\PaymentIntent;
use DateTime;

/**
 * @Route("/payement")
 */
class PayementController extends AbstractController
{
    /**
     * @Route("/", name="payement_index", methods={"GET"})
     */
    public function index(PayementRepository $payementRepository): Response
    {
        return $this->render('payement/index.html.twig', [
            'payements' => $payementRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new/{id}", name="payement_new", methods={"GET","POST"})
     */
    public function new(Campaign $campaign, Request $request, PayementRepository $payementRepository): Response
    {
        $payement = new Payement();
        $form = $this->createForm(PayementType::class, $payement);
        $form->handleRequest($request);
        $montant=$request->request->get("montant");
        
        // dd($payement);
        
        if ($form->isSubmitted() && $form->isValid()) {

            $payement->getParticipantId()->setCampaignId($campaign);

            Stripe::setApiKey('sk_test_51IuwAFEHR08MdWvwClmSXAvqn7j1Zl5W3hjQ856GZE2iz9o16Z5xu3jSDerQA0TJLoGHfkwN2IQwyMjvA6YKJN7P003HNA39NI');
            $paymentIntent = PaymentIntent::create([
                'amount' => $payement->getMontant()*100,
                'currency' => 'eur',
            ]);
            $output = [
                'clientSecret' => $paymentIntent->client_secret,
            ];
            
            // //Recupération de campagne grace à son id en GET
            // $idCampaign = explode('=', $request-> getQueryString())[1]; 
            // $campaignRepository = $this->getDoctrine()->getRepository(Campaign::class);
            // $campaign = $campaignRepository->find($idCampaign);
            
            
            //set les parametres manquants
            
            $payement->setCreatedAt(new DateTime());
            $payement->setUpdatedAt(new DateTime());
            $payement->getParticipantId()->setCampaignId($campaign);
            
            //envoi a la bdd
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($payement);
            $entityManager->flush();

            //redirection
            return $this->redirectToRoute('campaign_show', ['id' => $campaign->getId()]);
        }

        return $this->render('payement/new.html.twig', [
            'payement' => $payement,
            'form' => $form->createView(),
            'campaign' => $campaign,
            'montant' => $montant
        ]);
    }

    /**
     * @Route("/{id}", name="payement_show", methods={"GET"})
     */
    public function show(Payement $payement): Response
    {
        return $this->render('payement/show.html.twig', [
            'payement' => $payement,
        ]);
    }
    

    /**
     * @Route("/{id}/edit", name="payement_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Payement $payement): Response
    {
        $form = $this->createForm(PayementType::class, $payement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('payement_index');
        }

        return $this->render('payement/edit.html.twig', [
            'payement' => $payement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="payement_delete", methods={"POST"})
     */
    public function delete(Request $request, Payement $payement): Response
    {
        if ($this->isCsrfTokenValid('delete'.$payement->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($payement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('payement_index');
    }
}

templates/payement/_delete_form.html.twig
<form method="post" action="{{ path('payement_delete', {'id': payement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ payement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/payement/_form.html.twig
    <div class="container">
        <div class="section">
            <div class="row">
                <div class="col s12 center">
                    <h4>Participez en quelques secondes</h4>
                </div>
            </div>
            <!--   Form Section   -->
            <div class="card">
                <div class="card-content">
                    <div class="row">
                        {{ form_start(form) }}
                            <h5 class="center">Votre identité</h5>
                            <div class="input-field col s12 l6">
                               {{ form_widget(form.participant_id.mail_participant) }}
                               {{ form_label(form.participant_id.mail_participant) }}
                            </div>
                            <div class="input-field col s12 l6">

                            {% if montant is defined %}
                                {{ form_widget(form.montant,{
                                    "attr": {"min":"1","value":montant}
                                    }) }}
                             {% else %}
                                {{ form_widget(form.montant,{
                                    "attr": {"min":"1"}
                                    }) }}
                            {% endif %}
                        {{ form_label(form.montant,"montant",{"label_attr":{"class":"montant"}}) }}
                            </div>

                            <p>
                                <label>
                                    {{ form_widget(form.participant_id.is_anonymous) }}
                                    <span>Masquer mon identité auprès des autres participants</span>
                                </label>
                            </p>

             <div class="clearfix"></div>
                    <h5 class="center">Paiement</h5>
                    <div class="input-field col s12">
                        {# TODO Mettre l'input du participant id à la place  #}
                        <input id="card_name" type="text" class="validate">
                        <label for="card_name">Nom sur la carte</label>
                    </div>
                    <div class="input-field col s12" id="card-element">
                        <input id="card_number" type="text" class="validate">
                        <label id="card-element" for="card_number">Numéro de la carte</label>
                    </div>
                    <div class="input-field col s12 l6">
                        <a href="#!" class="btn btn-large waves-effect waves-light grey col s12">Annuler</a>
                    </div>
                    <div class="input-field col s12 l6">
                        <button class="btn btn-large waves-effect waves-light pink lighten-1 col s12" type="submit" name="action">
                            Participer
                            <i class="material-icons right">euro_symbol</i>
                        </button>
            </div>
    
 {{ form_end(form) }}
   <script src="{{asset ('assets/js/payement.js')}}"></script>
                       
                    </div>
                </div>
            </div>
        </div>
    </div>

templates/payement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Payement{% endblock %}

{% block body %}
    <h1>Edit Payement</h1>

    {{ include('payement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('payement_index') }}">back to list</a>

    {{ include('payement/_delete_form.html.twig') }}
{% endblock %}

templates/payement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Payement index{% endblock %}

{% block body %}
    <h1>Payement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Montant</th>
                <th>Participant_id</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for payement in payements %}
            <tr>
                <td>{{ payement.id }}</td>
                <td>{{ payement.montant }}</td>
                <td>{{ payement.createdAt ? payement.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ payement.updatedAt ? payement.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ payement.participantId }}</td>
                <td>
                    <a href="{{ path('payement_show', {'id': payement.id}) }}">show</a>
                    <a href="{{ path('payement_edit', {'id': payement.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('payement_new') }}">Create new</a>

    
{% endblock %}

templates/payement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Payement{% endblock %}

{% block body %}

   <div class="parallax-container valign-wrapper">
        <div class="section no-pad-bot">
            <div class="container">
                <h1 class="header center white-text light">{{ campaign.name }}</h1>
                <div class="row center">
                    <h5 class="header col s12 light">- Organisée par : {{ campaign.username }} -</h5>
                </div>
            </div>
        </div>
        <div class="parallax"><img src="/assets/images/8.jpg" alt="Titre de la campagne"></div>
    </div>
    

    {{ include('payement/_form.html.twig') }}

    <a href="{{ path('payement_index') }}">back to list</a>
{% endblock %}
{% block javascripts %}
    <script>
        let stripe = Stripe("pk_test_51IuwAFEHR08MdWvwKhCbOaT2odaZNHSwBQgUFgvb86dze0VxjuAAgTFdRF2k70jht1y4rsRNqnyhN9iXSRKkPPLw00bMYLfT5Y");
        // The items the customer wants to buy
        let elements = stripe.elements();

        var style = {
    base: {
    // Add your base input styles here. For example:
    fontSize: '16px',
    color: '#32325d',
    },
    };

    // Create an instance of the card Element.
    var card = elements.create('card', {style: style});

        // Add an instance of the card Element into the `card-element` <div>.
    card.mount('#card-element');
    </script>
    {% endblock %}

templates/payement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Payement{% endblock %}

{% block body %}
    <h1>Payement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ payement.id }}</td>
            </tr>
            <tr>
                <th>Montant</th>
                <td>{{ payement.montant }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ payement.createdAt ? payement.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ payement.updatedAt ? payement.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Participant_id</th>
                <td>{{ payement.participantId }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('payement_index') }}">back to list</a>

    <a href="{{ path('payement_edit', {'id': payement.id}) }}">edit</a>

    {{ include('payement/_delete_form.html.twig') }}
{% endblock %}