src/Entity/Participants.php
<?php

namespace App\Entity;

use App\Repository\ParticipantsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ParticipantsRepository::class)
 */
class Participants
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mail_participant;

  /**
     * @ORM\ManyToOne(targetEntity=Campaign::class, inversedBy="participants")
     * @ORM\JoinColumn(nullable=false)
     */
    private $campaign_id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_anonymous;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getMailParticipant(): ?string
    {
        return $this->mail_participant;
    }

    public function setMailParticipant(string $mail_participant): self
    {
        $this->mail_participant = $mail_participant;

        return $this;
    }

    public function getCampaignId(): ?Campaign
    {
        return $this->campaign_id;
    }

    public function setCampaignId(?Campaign $campaign_id): self
    {
        $this->campaign_id = $campaign_id;

        return $this;
    }

    public function getIsAnonymous(): ?bool
    {
        return $this->is_anonymous;
    }

    public function setIsAnonymous(bool $is_anonymous): self
    {
        $this->is_anonymous = $is_anonymous;

        return $this;
    }
}

src/Form/ParticipantsType.php
<?php

namespace App\Form;

use App\Entity\Participants;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ParticipantsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('mail_participant')
            ->add('is_anonymous')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Participants::class,
        ]);
    }
}

src/Controller/ParticipantsController.php
<?php

namespace App\Controller;

use App\Entity\Participants;
use App\Form\ParticipantsType;
use App\Repository\ParticipantsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/participants")
 */
class ParticipantsController extends AbstractController
{
    /**
     * @Route("/", name="participants_index", methods={"GET"})
     */
    public function index(ParticipantsRepository $participantsRepository): Response
    {
        return $this->render('participants/index.html.twig', [
            'participants' => $participantsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="participants_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $participant = new Participants();
        $form = $this->createForm(ParticipantsType::class, $participant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($participant);
            $entityManager->flush();

            return $this->redirectToRoute('participants_index');
        }

        return $this->render('participants/new.html.twig', [
            'participant' => $participant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="participants_show", methods={"GET"})
     */
    public function show(Participants $participant): Response
    {
        return $this->render('participants/show.html.twig', [
            'participant' => $participant,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="participants_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Participants $participant): Response
    {
        $form = $this->createForm(ParticipantsType::class, $participant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('participants_index');
        }

        return $this->render('participants/edit.html.twig', [
            'participant' => $participant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="participants_delete", methods={"POST"})
     */
    public function delete(Request $request, Participants $participant): Response
    {
        if ($this->isCsrfTokenValid('delete'.$participant->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($participant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('participants_index');
    }
}

templates/participants/_delete_form.html.twig
<form method="post" action="{{ path('participants_delete', {'id': participant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ participant.id) }}">
    <button class="btn">Delete</button>
</form>

templates/participants/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/participants/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Participants{% endblock %}

{% block body %}
    <h1>Edit Participants</h1>

    {{ include('participants/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('participants_index') }}">back to list</a>

    {{ include('participants/_delete_form.html.twig') }}
{% endblock %}

templates/participants/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Participants index{% endblock %}

{% block body %}
    <h1>Participants index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Mail_participant</th>
                <th>Campaign_id</th>
                <th>Is_anonymous</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for participant in participants %}
            <tr>
                <td>{{ participant.id }}</td>
                <td>{{ participant.name }}</td>
                <td>{{ participant.mailParticipant }}</td>
                <td>{{ participant.campaignId }}</td>
                <td>{{ participant.isAnonymous ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('participants_show', {'id': participant.id}) }}">show</a>
                    <a href="{{ path('participants_edit', {'id': participant.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('participants_new') }}">Create new</a>
{% endblock %}

templates/participants/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Participants{% endblock %}

{% block body %}
    <h1>Create new Participants</h1>

    {{ include('participants/_form.html.twig') }}

    <a href="{{ path('participants_index') }}">back to list</a>
{% endblock %}

templates/participants/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Participants{% endblock %}

{% block body %}
    <h1>Participants</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ participant.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ participant.name }}</td>
            </tr>
            <tr>
                <th>Mail_participant</th>
                <td>{{ participant.mailParticipant }}</td>
            </tr>
            <tr>
                <th>Campaign_id</th>
                <td>{{ participant.campaignId }}</td>
            </tr>
            <tr>
                <th>Is_anonymous</th>
                <td>{{ participant.isAnonymous ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('participants_index') }}">back to list</a>

    <a href="{{ path('participants_edit', {'id': participant.id}) }}">edit</a>

    {{ include('participants/_delete_form.html.twig') }}
{% endblock %}